# Generated by Django 2.2.6 on 2019-11-01 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_auto_20191101_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redaction',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='redaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='p_library.Redaction'),
            preserve_default=False,
        ),
    ]
