# Generated by Django 2.2.6 on 2019-11-12 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0006_auto_20191112_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspiration',
            name='inspirer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspired_works', to='p_library.Author'),
        ),
    ]
